### ISSUE TITLE
PostCSSのバージョンを8系に更新する

### ISSUE THREAD

**Issue by keitakn** [nekochans/kimono-app-frontend#48]
# Doneの定義
- `postcss` のprefixが付いたpackageが最新安定版に更新されている事

 # 補足情報
以下のエラーが発生してしまう。

```
ERROR in ./node_modules/@storybook/addon-info/dist/components/PropTable/style.css (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/@storybook/core/node_modules/postcss-loader/src??ref--7-2!./node_modules/@storybook/addon-info/dist/components/PropTable/style.css)
Module build failed (from ./node_modules/@storybook/core/node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin postcss-import requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/kogakeita/gitrepos/kimono-app-frontend/node_modules/@storybook/core/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/Users/kogakeita/gitrepos/kimono-app-frontend/node_modules/@storybook/core/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/kogakeita/gitrepos/kimono-app-frontend/node_modules/@storybook/core/node_modules/postcss/lib/postcss.js:55:10)
    at /Users/kogakeita/gitrepos/kimono-app-frontend/node_modules/@storybook/core/node_modules/postcss-loader/src/index.js:140:12
 @ ./node_modules/@storybook/addon-info/dist/components/PropTable/style.css 2:26-166 53:4-74:5 56:18-158
 @ ./node_modules/@storybook/addon-info/dist/components/PropTable/components/Table.js
 @ ./node_modules/@storybook/addon-info/dist/components/PropTable/index.js
 @ ./node_modules/@storybook/addon-info/dist/index.js
 @ ./.storybook/config.js
 @ ./.storybook/config.js-generated-config-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/config.js-generated-config-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

https://github.com/postcss/postcss-import/issues/435 がとの関連性を調査しアップデートを実施する。

**Comment by keitakn** [comment]
https://github.com/nekochans/kimono-app-frontend/pull/63 で本件も解決するので、https://github.com/nekochans/kimono-app-frontend/pull/63 がマージされたら本件もクローズする。
